### ISSUE TITLE
All transcripts strand are forward (+)

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/ANGEL#11]
Hi @Magdoll,
 I have successfully ran ANGEL got results.  i'm confused why are they all the same strand(+) in 'AD_Angel.ANGEL.pep' file. But in the initial fasta file, It is reverse strand, for example PB.3.2 in files(shown on screenshot ), By the way, I didn't use the parameter "--use_rev_strand", is that reason, i'm not sure.

![2](https://user-images.githubusercontent.com/20789616/27999482-367c21ce-6550-11e7-9cf9-92192cda2c25.jpg)
![3](https://user-images.githubusercontent.com/20789616/27999483-367d4cac-6550-11e7-875e-e8ff502b2929.jpg)

**Comment by Magdoll** [comment]
Hi @linglingtingfei ,

the "-" strand you saw in the initial file (where you highlighted) indicates this transcript is on the - strand of the chromosome. It has nothing to do with which strand ANGEL is predicting on.

Since you then ran ANGEL predict without `--use_rev_strand`, all the results are hence in +, so you see `strand:+` only.

--Liz
