### ISSUE TITLE
angel_predict.py gets stuck and does nothing

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/ANGEL#8]
@nlhepler @Magdoll  , I have been successfully run with dumb_predict.py, angel_make_training_set.py, angel_train.py but angel_predict.py hangs and does nothing suddenly.  I've tried it several times , and the results are the same.
503G server memory is available. The size of fasta file is 50.82MB(36314  sequences), the number of CPU i used is 8. 
I'm looking forward to your reply.

**Comment by linglingtingfei** [comment]
This issue has been resolved. Please close the thread. Thanks!

**Comment by tabotaab** [comment]
Hi @Magdoll , I have the same problem with Last Updated: 11/8/2016 version 2.3. 
angel_predict.py hangs and does nothing suddenly. I tried default number of CPUs and even more CPUs. 
Looking fwd to hearing from you

**Comment by Magdoll** [comment]
Did you check that the memory usage with `free -g`? And confirmed it is hanging with `top` to check process? How big is in the input dataset? How many sequences?

**Comment by achurcher** [comment]
Hi @Magdoll 
I also appear to be having the same problem. We have a set of 51887 sequences (149Mb) and are running ANGEL v2.3. The 'angel_predict.py' script seems to be getting stuck quite early on the the run. I have tried using 8 and 12 CPUs (with 256Gb mem). It does not appear to be a memory issue at the point where the runs seem to get stuck. Do you have any suggestions?

Thanks in advance!!

**Comment by Magdoll** [comment]
Hi @achurcher ,

Until I fix this issue fundamentally, here is a quick fix (and sorry it requires more manual work):
--- first kill off all existing angel_predict.py processes
--- go into the temporary directory created in the killed run (will look like `ANGEL.tmp.xxxx`), run each of the split up fasta files using single CPUs `angel_predict.py --cpus 1`. This way you get around the Python multiprocessing module issue with hanging. Once each split is completed, you can simply concatenate all the result files together. (ex: cat ANGEL.tmp.xxx/*.cds > combined.ANGEL.cds)

Let me know how this goes.

--Liz

**Comment by achurcher** [comment]
Hi Liz
Thanks for your reply. This doesn't seem to have fixed the issue. I have tried with a couple of different test sets and the runs seem to hang at different places depending on the input set of sequences. 

I have pasted part of the stderr below in case that is helpful. I would be happy to hear if you have any more suggestions

Thanks in advance!

stderr:
Reading classifer pickle: classifier.pickle
Splitting input into chunks for parallelization....
Pool worker for ANGEL.tmp.1490345004/test_out.split_0.fa
predicting for c25867/f1p4/1551_isoform=c25867;full_length_coverage=1;non_full_length_coverage=4;isoform_length=1551
/home/allisonc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/Bio/Seq.py:343: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)
writing result for c25867/f1p4/1551_isoform=c25867;full_length_coverage=1;non_full_length_coverage=4;isoform_length=1551 to ANGEL.tmp.1490345004/test_out.split_0.fa.ANGEL
predicting for c25868/f1p1/1897_isoform=c25868;full_length_coverage=1;non_full_length_coverage=1;isoform_length=1897
/home/allisonc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/Bio/Seq.py:2041: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
writing result for c25868/f1p1/1897_isoform=c25868;full_length_coverage=1;non_full_length_coverage=1;isoform_length=1897 to ANGEL.tmp.1490345004/test_out.split_0.fa.ANGEL
predicting for c25870/f1p3/1555_isoform=c25870;full_length_coverage=1;non_full_length_coverage=3;isoform_length=1555
writing result for c25870/f1p3/1555_isoform=c25870;full_length_coverage=1;non_full_length_coverage=3;isoform_length=1555 to ANGEL.tmp.1490345004/test_out.split_0.fa.ANGEL
predicting for c25873/f1p1/1984_isoform=c25873;full_length_coverage=1;non_full_length_coverage=1;isoform_length=1984
. . .

**Comment by zhukesen** [comment]
Hi @Magdoll
I also appear to be having the same problem,The 'angel_predict.py' script seems to be getting stuck quite early on the the run.

**Comment by TomDrewJim** [comment]
Hi @Magdoll 
I met with the same problem that the progam got stuck with a few sub mission finished.  Maybe there are some bugs of multithreading modules in version v2.7 ?
- TomDrewJim

**Comment by TomDrewJim** [comment]
Hi, I found out the v2.7 suffered  the same problem and it worked out when canceling "--use_rev_strand"

**Comment by xinkaitong** [comment]
> Hi, I found out the v2.7 suffered the same problem and it worked out when canceling "--use_rev_strand"

Hello, i got the same problem as you. however, if we cancel the "--use_rev_strand", what effect would it have on results.

**Comment by TomDrewJim** [comment]
> > Hi, I found out the v2.7 suffered the same problem and it worked out when canceling "--use_rev_strand"
> 
> Hello, i got the same problem as you. however, if we cancel the "--use_rev_strand", what effect would it have on results.

I'm not sure because I have no comparison of tow methods.  But the manual of PacBio said the direction of reads is 5' to 3'. Maybe it has no effect.

**Comment by xinkaitong** [comment]
Hello! @Magdoll 
I met with the same problem, but i didn't think there were some wrong with multithread. When i input only a sequence into angel_predict.py with option " --use_rev_strand --cups 1 ", it was still stuck. However, when the option " --use_rev_strand " was canceled, program finished. Are there some effects on results without option " --use_rev_strand "?

**Comment by xinkaitong** [comment]
> > > Hi, I found out the v2.7 suffered the same problem and it worked out when canceling "--use_rev_strand"
> > 
> > 
> > Hello, i got the same problem as you. however, if we cancel the "--use_rev_strand", what effect would it have on results.
> 
> I'm not sure because I have no comparison of tow methods. But the manual of PacBio said the direction of reads is 5' to 3'. Maybe it has no effect.

Yes, there are two strands in 5' to 3' produced after pacbio sequencing, but it's only one strand whose base order was the same as isoform. what we want to predict is the isoform's CDS and UTR, right?
