### ISSUE TITLE
Complete cds or partial cds?

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/ANGEL#9]
@nlhepler @Magdoll 
Each ANGEL output sequence ID has fixed format.**completeness** is either complete, 5partial, 3partial, or internal based on the presence or absence of start and stop codons.
In my opinion,  **completeness** indicates that the sequence has complete ORF. But I want to know whether **completeness** also means there is complete cds or not? You know, ORF is different from CDS. In my ANGEL output results, a full-length transcript(PB.422.1) has complete ORF but why there is only 3'UTR  and no 5'UTR while other transcripts have both of them.  I am anticipating your reply.

![cds](https://cloud.githubusercontent.com/assets/20789616/19877256/96384a0a-a018-11e6-8a92-898b825e4f43.jpg)
![utr](https://cloud.githubusercontent.com/assets/20789616/19877257/963af2fa-a018-11e6-810a-18ce1e3f71d9.png)

**Comment by Magdoll** [comment]
@linglingtingfei ,

"complete CDS" means the presence of a start codon "ATG" and a stop codon "TAA/TGA/TAG". 
"5-partial" means there's a stop codon but no start codon (which can happen because the Clontech SMARTer kit doesn't do cap trap so you can get degraded 5' ends missing the start codon); "3-partial" which is quite rare means the stop codon is missing.

There is a minimum length UTR length of 50 bp (right now it's hard-coded). Any UTR length shorter than that will not be output.

--Liz
